swagger: '2.0'
info:
  description: Leinster Hockey Rest API
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: leinsterhockey@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: cards.leinsterhockey.ie
basePath: /cards/fuel/public
schemes:
  - http
paths:
  /cards:
    get:
      summary: Gets all cards
      produces:
        - text/html
        - application/json
      parameters:
        - name: q
          in: query
          type: string
          description: 'Query to search in cards: club, competition, date or id'
      responses:
        '200':
          description: Valid request
      security:
        - petstore_auth:
            - 'read:cards'
  '/cards/{id}':
    get:
      summary: Gets a specific card
      produces:
        - text/html
        - application/json
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Fixture ID as number or card ID with 'n' in front
      responses:
        '200':
          description: Valid request
