# vim: et:ts=4:sw=4:ai
server {
    if ($host = cards.squarepig.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name cards.squarepig.dev;
    return 404; # managed by Certbot


}
server {
    server_name cards.squarepig.dev;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/cards.squarepig.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cards.squarepig.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # Site configuration
    root /home/deploy/sites/cards.leinsterhockey.ie/code/public;
    index index.php index.html;

    rewrite_log on;

    access_log /var/log/nginx/cards_access.log;
    error_log  /var/log/nginx/cards_error.log info;

	# -----------------
    # Python API proxy
    # -----------------
    location /api/v2/ {
        proxy_pass http://127.0.0.1:8000/;   # adjust port to match your Python service
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # -----------------
    # FuelPHP defaults
    # -----------------
    location ~ ^/check.php { }
    location ~ ^/cards/.*(?<!\.php)$ { }
    location ~ ^/cards/ui/.*$ { }
    location ~ ^/assets/.*$ { }
    location ~ ^/index.php/.* { }

    location / {
       rewrite ^/$ /user/login;
       rewrite ^/api/1.0/(.*)$ /api/$1;

       set $save_uri $uri;
       rewrite ^(.*(?<!\.php))$ /index.php?$query_string;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass 127.0.0.1:9001;
        fastcgi_index index.php;
        fastcgi_param REQUEST_URI $save_uri;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}

